# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z639TmF7Z3okMt-v5unyAX3CUP-efw3h
"""

from google.colab import drive
drive.mount("/content/drive/")

import fnmatch, os
dir_path = "/content/drive/"
count = 0
for path in os.listdir(dir_path):
    if os.path.isfile(os.path.join(dir_path, path)):
        count += 1

def get_data(num):
 while True:
  N= 0
  for i in range(N,num):
    get_ipython().system('python detect.py --weights runs/train/yolov5_results/weights/best.pt --img $IMG_SIZE --conf 0.4 --source ("{0}/{1}.jpg", format(dir_path, i))')
  # 라벨 데이터 찾아서 정리하기 
    file = open(("{0}/labels/{1}.txt", format(dir_path,i)), mode = 'r', encoding = 'utf-8')
    lines = file.readlines() 
    for line in lines:
      line = line.split(' ')
      line = [line.strip() for i in line] #Txt 파싱 데이터 중 값 추출
    if line[0] != "0":
      signal_number = 1 #fall
      N = i # i번째를 시작하는 순서로 정하기
      continue
    else:
      signal_number = 0 #no fall
      break

get_data(count)